### ISSUE TITLE
CI's kill house targets broken

### ISSUE THREAD

**Issue by EdwinCNdev** [civilnetworks-projects/SCP_Public_Development#615] opened 2024-05-25 23:53 UTC
**Description**
CI's targets doesn't have a hitbox to register shots for it to proceed with the rest of the course

**Steps to Reproduce**
1. Run the kill house
2. Try to shoot the first target
3.

**Expected Behaviour**
The targets are supposed to go down and the door to the left open to the next room

**Actual Behaviour**
No hits being registered on the target

**Evidence**
https://medal.tv/games/garrys-mod/clips/2dlKAmqyGTrrSf/d1337WaAatUE?invite=cr-MSxycU4sNzExMzQ5Mjcs

**Comment by CNCanoon** [comment] 2024-10-10 19:56
To be checked by Content.

**Comment by Naffenz** [comment] 2024-10-11 19:54
Still a bug

**Comment by HerrKvarkar** [comment] 2024-10-25 10:56
Duplicate of #544 on Private

**Closed as not planned by HerrKvarkar** 2024-10-25 10:56 UTC
Labels: bug
