### ISSUE TITLE
SCP Fracture Bug

### ISSUE THREAD

**Issue by EdwinCNdev** [civilnetworks-projects/SCP_Public_Development#663] opened 2024-07-23 21:28 UTC
**Description**
SCPs are able to have fractures that Impede gameplay.

**Steps to Reproduce**
(From what I and Snake found)
1. get a fracture on any job that is not SCP
2. Swap on an SCP like 7722 or 9000 A2 (2 documented cases that it has occurred on)
3. The Fracture carries over if you have a leg/arm fracture on an SCP

**Expected Behaviour**
SCPs shouldn't be able to get fractured

**Actual Behaviour**
SCP was able to be fractured

**Evidence**
https://medal.tv/games/garrys-mod/clips/ijat05VhItZDxc5WL/d1337llb6CHY?invite=cr-MSx5aHIsMjE1NzQ5NDI4LA
https://medal.tv/games/garrys-mod/clips/ijazkWL9aAxI-jibJ/d1337svrkUgX?invite=cr-MSx2aUosMjE1NzQ5NDI4LA

**Comment by HerrKvarkar** [comment] 2024-10-25 10:40
Duplicate of #529

**Closed as not planned by HerrKvarkar** 2024-10-25 10:40 UTC
