### ISSUE TITLE
Elastic Restraints Bugged Viewmodel

### ISSUE THREAD

**Issue by auburncivilnetworks** [civilnetworks-projects/SCP_Public_Development#556] opened 2024-03-14 07:22 UTC
### Description
Elastic Restraints lost visible view model. View model of cuffs is bugged into head

### Steps to Reproduce
1. Hold out elastic restraints - View model not even there
2. Move mouse left to right - to see cuff model

### Expected Behavior
Regular elastic restraint view model is visible.

### Actual Behavior
Elastic restraints are invisible and bugged into the camera. 

### Evidence
https://medal.tv/games/garrys-mod/clips/1Nx1mkmynKpHQv/d1337OOEwnAs?invite=cr-MSxsTE8sMjM3NjUzMjks

**Comment by auburncivilnetworks** [comment] 2024-03-14 07:22
https://medal.tv/games/garrys-mod/clips/1Nx6cPzs2Y12rc/d1337dWVZQnP?invite=cr-MSx0MzIsMjM3NjUzMjks

**Comment by CNCanoon** [comment] 2024-10-10 19:56
To be checked by Content.

**Comment by CNCanoon** [comment] 2024-10-11 20:01
Still an issue.

**Comment by emilsnat** [comment] 2024-11-24 00:11
Duplicate of #501

**Closed as not planned by emilsnat** 2024-11-24 00:11 UTC
Labels: bug
