### ISSUE TITLE
Add an announcement when sitewide lockdown is enabled

### ISSUE THREAD

**Issue by Solid-Snake420** [civilnetworks-projects/SCP_Public_Development#759] opened 2024-11-10 22:21 UTC
https://civilnetworks.net/community/threads/site-wide-lockdown-qol.28745/

**Enhancement description**
It would involve adding an announcement via the facility announcement system voice telling people that "Site wide lockdown is enabled. Seek shelter".

**Specification**
This would be activated when sitewide lockdown is toggled and would also come up in text and the facility announcement voice.

**Comment by JacubRSTNC** [comment] 2024-11-20 18:23
Duplicate of https://github.com/civilnetworks-projects/SCP_Private_Development/issues/323

**Closed as not planned by JacubRSTNC** 2024-11-20 18:23 UTC
Labels: enhancement
