### ISSUE TITLE
Random reload bug

### ISSUE THREAD

**Issue by Solid-Snake420** [civilnetworks-projects/SCP_Public_Development#746] opened 2024-10-24 21:44 UTC
**Description**
Gun randomly decides to reload even playing the sound yet not actually reloading it, requires you to swap weapons to allow you to shoot again

**Steps to Reproduce**
Unfortunately this bug is seemingly random however anyone who plays on a regular basis will have experienced it at one point.

**Expected Behaviour**
It would reload properly and only do so when you press the R key.

**Actual Behaviour**
If your magazine is not full it can randomly decide to reload mid combat.

**Evidence**
https://medal.tv/games/garrys-mod/clips/iPCvYSZ5LkgOY_FEO?invite=cr-MSxoekIsMTU4NTA0NDU5LA

**Comment by HerrKvarkar** [comment] 2024-10-25 10:54
Duplicate of #692

**Closed as not planned by HerrKvarkar** 2024-10-25 10:54 UTC
Labels: bug
