### ISSUE TITLE
Fractures carry over to SCPs

### ISSUE THREAD

**Issue by Solid-Snake420** [civilnetworks-projects/SCP_Public_Development#673] opened 2024-08-04 16:59 UTC
Thread title - SCPs can have fractures

Description
SCPs being able to have fractures that Impeed on gameplay, such as a leg fracture reducing the speed your SCP is able to move at when they should be much faster.  Also the Arm fracture stopping from them swapping weapons, which is a BIG issues for namely scps such as Type Green, but also an issue if you want to use a breach tool as you are unable to swap due to having a fracture

Steps to Reproduce
(From what me and snake found)
get a fracture on any job that is not SCP
Swap on an SCP like 7722 or 9000 A2 (2 documented cases that it has occured on)
The Fracture carries over you have a leg / arm fracture on an SCP

Expected Behaviour
SCPs shouldnt be able to get fractured

Actual Behaviour
SCP was able to be fractured

Evidence
https://medal.tv/games/garrys-mod/clips/ijat05VhItZDxc5WL/d1337llb6CHY?invite=cr-MSx5aHIsMjE1NzQ5NDI4LA
https://medal.tv/games/garrys-mod/clips/ijazkWL9aAxI-jibJ/d1337svrkUgX?invite=cr-MSx2aUosMjE1NzQ5NDI4LA

**Comment by HerrKvarkar** [comment] 2024-10-25 10:40
Duplicate of #529

**Closed as not planned** 2024-10-25 10:39 UTC
Labels: bug
