### ISSUE TITLE
ERT being able to heal up to 600HP

### ISSUE THREAD

**Issue by Rushi123456** [civilnetworks-projects/SCP_Public_Development#467] opened 2023-11-01 20:30 UTC
https://www.civilgamers.com/community/threads/allow-ert-to-heal-back-to-600-hp.19647/

**Description**: Essentially, ERT is only able to heal to 100 HP (unsure if it's because of the medkit itself, or ERT max HP not being set to 600?).

**Comment by auburncivilnetworks** [comment] 2024-10-05 21:24
Duplicate of https://github.com/civilnetworks-projects/SCP_Public_Development/issues/684

**Closed by auburncivilnetworks** 2024-10-05 21:24 UTC
Labels: enhancement
