### ISSUE TITLE
Making skills universal for all characters

### ISSUE THREAD

**Issue by Raptor731** [civilnetworks-projects/SCP_Public_Development#586] opened 2024-04-17 21:14 UTC
https://www.civilgamers.com/community/threads/make-looting-and-cooking-levels-universal.24101/

**Enhancement description**
This will make both of the looting and and cooking skills universal to all characters.

**Comment by JacubRSTNC** [comment] 2024-09-10 13:47
Duplicate of #582

**Closed as not planned by JacubRSTNC** 2024-09-10 13:47 UTC
Labels: enhancement
